wip: organize functions in logical sections

diff --git a/function b/function
--- a/function
+++ b/function
@@ -9,102 +9,6 @@
 ####
 
 #####
-# If one value is given, mkdir -p plus cd is called.
-# If multiple values are given. mkdir is called.
-#
-# @param string $# - string name of directory you want to create
-#
-# @author stev leibelt
-# @since 2013-01-05
-####
-function net_bazzline_mkdir ()
-{
-    #check if at least one argument is supplied
-    if [[ $# -eq 0 ]]; then
-        echo "No arguments supplied"
-        return 1
-    fi
-
-    #if one argument is supplied, create dir and
-    # change to it
-    if [[ $# -eq 1 ]]; then
-        mkdir -p "$1" 
-        cd "$1"
-        return 0
-    fi
-
-    #if more then one argument is supplied
-    # execute default mkdir
-    if [[ $# -gt 1 ]]; then
-        mkdir $@
-        return 0
-    fi
-}
-
-####
-# create a directory with a prefix of current date (Ymd)
-#
-# @param string $1 - directory name you want to create
-#
-# @author stev leibelt
-# @since 2013-03-08
-####
-function net_bazzline_mkdirPrefixCurrentDate ()
-{
-    if [[ $# -eq 1 ]]; then
-        directoryName=`eval date +%y%m%d`"_$1"
-
-        net_bazzline_mkdir "$directoryName"
-    else
-        echo 'Should be called with exactly one parameter'
-    fi
-}
-
-####
-# create a file with a prefix of current date (Ymd)
-#
-# @param string $1 - file name you want to create
-#
-# @author stev leibelt
-# @since 2014-09-20
-####
-function net_bazzline_touchPrefixCurrentDate ()
-{
-    if [[ $# -eq 1 ]]; then
-        directoryName=`eval date +%y%m%d`"_$1"
-
-        touch "$directoryName"
-    else
-        echo 'Should be called with exactly one parameter'
-    fi
-}
-
-#####
-# You can change $i levels by using cd $i
-#
-# @param mixed $1 - [optional] path where you want do change
-#                       or number of directories you want to
-#                       change upwards - default is $HOME
-#
-# @author stev leibelt
-# @since 2013-01-30
-####
-function net_bazzline_cd ()
-{
-    #is numeric value?
-    if [[ $# -eq 0 ]]; then 
-        cd "$HOME"
-    elif [[ `expr $1 + 1 2> /dev/null` ]]; then
-        for (( i=1; i <= $1; i++))
-        do
-            cd ..
-        done
-    else
-        \cd "$1"
-    fi
-}
-
-#####
 # Combines ps aux and grep
 #
 # @param string $1 - pattern your are searching for
@@ -342,53 +246,6 @@ function net_bazzline_burn ()
 }
 
 ####
-# calles find with given param and type f
-#
-# @param string $1 - pattern you are searching for
-# @param [string $2] - path to serching in
-# @param [bool $3] - do not ignore dot files
-#
-# dot exclusion taken from: https://www.linuxquestions.org/questions/linux-general-1/find-and-excluding-all-hidden-directories-910578/
-#
-# @author stev leibelt
-# @since 2013-03-08
-####
-function net_bazzline_find_file ()
-{
-    if [[ $# -eq 1 ]]; then
-        find . -iname "$1" -not -path "*/.*/*" -not -name ".*" -type f 2>/dev/null
-    elif [[ $# -eq 2 ]]; then
-        find "$2"  -iname "$1" -not -path "*/.*/*" -not -name ".*" -type f 2>/dev/null
-    elif [[ $# -eq 3 ]]; then
-        find "$2" -iname "$1" -type f 2>/dev/null
-    else
-        echo 'No valid argument supplied.'
-        return 1
-    fi
-}
-
-####
-# calles find with given param and type d
-#
-# @param string $1 - pattern your are searching for
-# @param [string $2] - path to serching in
-#
-# @author stev leibelt
-# @since 2013-03-08
-####
-function net_bazzline_find_directory ()
-{
-    if [[ $# -eq 1 ]]; then
-        find . -iname "$1" -type d 2>/dev/null
-    elif [[ $# -eq 2 ]]; then
-        find "$2" -iname "$1" -type d 2>/dev/null
-    else
-        echo 'No valid argument supplied.'
-        return 1
-    fi
-}
-
-####
 # refresh given interface
 #
 # @param string $1 - [optional] interface - default eth0
@@ -423,25 +280,6 @@ function net_bazzline_refresh_interface ()
     sudo ip link set $INTERFACE down
     sudo ip link set $INTERFACE up
     sudo dhcpcd $INTERFACE
-}
-
-####
-# Show differences between two directories
-#
-# @param string $1 - path to first directory
-# @param string $2 - path to second directory
-# 
-# @author stev leibelt <artodeto@bazzline.net>
-# @since 2013-05-21
-function net_bazzline_diff_directory ()
-{
-    if [[ $# -eq 2 ]]; then
-        diff -qr "$1" "$2" | sort
-    else
-        echo 'No valid argument supplied.'
-        echo 'Try command directory1 directory2'
-        return 1
-    fi
 }
 
 ####
@@ -961,50 +799,6 @@ function net_bazzline_what_is_listening_on_that_port()
 }
 
 ####
-# adds "." to the beginning of the directory or file name
-# 
-# @param string $1 - file system object identifier
-#
-# @author stev leibelt <artodeto@bazzline.net>
-# @since 2014-07-31
-####
-function net_bazzline_hide_file_system_object()
-{
-    if [[ $# -eq 1 ]]; then
-# @todo validate if identifier is file or directory and if first character is not "."
-# @todo use net_bazzline_stringStartsWith
-        mv "$1" ."$1"
-    else
-        echo "Usage: net_bazzline_unhide_directory <directory_name>"
-        return 1
-    fi
-}
-
-####
-# adds "." to the beginning of the directory or file name
-#
-# @author stev leibelt <artodeto@bazzline.net>
-# @since 2014-07-31
-####
-function net_bazzline_unhide_file_system_object()
-{
-    if [[ $# -eq 1 ]]; then
-        IDENTIFIER="$1";
-# @todo validate if identifier is file or directory and if first character is "."
-# @todo use net_bazzline_stringStartsWith
-        #if [[ net_bazzline_stringStartsWith $IDENTIFIER "." ]]; then
-            mv $IDENTIFIER ${IDENTIFIER:1};
-            return 0
-        #else
-            #echo $IDENTIFIER" has to start with ."
-            #return 1
-    else
-        echo "Usage: net_bazzline_unhide_directory <directory_name>"
-        return 1
-    fi
-}
-
-####
 # validates if string starts with given string or not
 # 
 # @param string $1 - string
@@ -1400,86 +1194,6 @@ function net_bazzline_git_update_all_repositories()
 }
 
 ####
-# begin of zfs section
-####
-
-####
-# @param string <name of the zfs pool>
-# [@param string <name of the snapshot>, default is current date
-####
-function net_bazzline_create_zfs_snapshot()
-{
-    if [[ $# -lt 1 ]]; then
-        echo 'invalid number of arguments'
-        echo '    net_bazzline_create_zfs_snapshot <name of the zfs pool> [<name of the snapshot>]'
-        return 1
-    fi
-
-    NAME_OF_THE_POOL="$1"
-
-    if [[ $# -gt 1 ]]; then
-        NAME_OF_THE_SNAPSHOT="$2"
-    else
-        NAME_OF_THE_SNAPSHOT=$(date +'%Y-%m-%d_%H-%M-%S')
-    fi
-
-    if sudo zfs snapshot -r $NAME_OF_THE_POOL@$NAME_OF_THE_SNAPSHOT; then
-        echo 'snapshot "'$NAME_OF_THE_SNAPSHOT'" created for pool "'$NAME_OF_THE_POOL'"'
-    fi
-
-    return $?
-}
-
-####
-# @param string <name of zfs pool>
-# @param string <name of the snapshot>
-####
-function net_bazzline_delete_zfs_snapshot()
-{
-    if [[ $# -lt 2 ]]; then
-        echo 'invalid number of arguments'
-        echo '    net_bazzline_delete_zfs_snapshot <name of the zfs pool> [<name of the snapshot>]'
-        return 1
-    fi
-
-    NAME_OF_THE_POOL="$1"
-    NAME_OF_THE_SNAPSHOT="$2"
-
-    if sudo zfs destroy -R $NAME_OF_THE_POOL@$NAME_OF_THE_SNAPSHOT; then
-        echo 'snapshot "'$NAME_OF_THE_SNAPSHOT'" deleted from pool "'$NAME_OF_THE_POOL'"'
-    fi
-
-    return $?
-}
-
-####
-# [@param string <path to zfs pool>]
-####
-function net_bazzline_list_zfs_snapshots()
-{
-    if [[ $# -lt 1 ]]; then
-        sudo zfs list -t snapshot
-    else
-        NAME_OF_THE_POOL="$1"
-
-        sudo zfs list -t snapshot | grep $NAME_OF_THE_POOL
-    fi
-}
-
-####
-# @param string <path to zfs pool>
-# [@param int number of snapshots to keep, default is 1]
-####
-function net_bazzline_rotate_zfs_snapshot()
-{
-    echo 'work in progress'
-}
-
-####
-# end of zfs section
-####
-
-####
 # begin of ssh section
 ####
 
@@ -1551,6 +1265,212 @@ function net_bazzline_update_vim_bundles_and_plugins_with_vundle()
 ####
 # begin of filesystem section
 ####
+
+#####
+# If one value is given, mkdir -p plus cd is called.
+# If multiple values are given. mkdir is called.
+#
+# @param string $# - string name of directory you want to create
+#
+# @author stev leibelt
+# @since 2013-01-05
+####
+function net_bazzline_mkdir ()
+{
+    #check if at least one argument is supplied
+    if [[ $# -eq 0 ]]; then
+        echo "No arguments supplied"
+        return 1
+    fi
+
+    #if one argument is supplied, create dir and
+    # change to it
+    if [[ $# -eq 1 ]]; then
+        mkdir -p "$1" 
+        cd "$1"
+        return 0
+    fi
+
+    #if more then one argument is supplied
+    # execute default mkdir
+    if [[ $# -gt 1 ]]; then
+        mkdir $@
+        return 0
+    fi
+}
+
+####
+# create a directory with a prefix of current date (Ymd)
+#
+# @param string $1 - directory name you want to create
+#
+# @author stev leibelt
+# @since 2013-03-08
+####
+function net_bazzline_mkdirPrefixCurrentDate ()
+{
+    if [[ $# -eq 1 ]]; then
+        directoryName=`eval date +%y%m%d`"_$1"
+
+        net_bazzline_mkdir "$directoryName"
+    else
+        echo 'Should be called with exactly one parameter'
+    fi
+}
+
+####
+# create a file with a prefix of current date (Ymd)
+#
+# @param string $1 - file name you want to create
+#
+# @author stev leibelt
+# @since 2014-09-20
+####
+function net_bazzline_touchPrefixCurrentDate ()
+{
+    if [[ $# -eq 1 ]]; then
+        directoryName=`eval date +%y%m%d`"_$1"
+
+        touch "$directoryName"
+    else
+        echo 'Should be called with exactly one parameter'
+    fi
+}
+
+#####
+# You can change $i levels by using cd $i
+#
+# @param mixed $1 - [optional] path where you want do change
+#                       or number of directories you want to
+#                       change upwards - default is $HOME
+#
+# @author stev leibelt
+# @since 2013-01-30
+####
+function net_bazzline_cd ()
+{
+    #is numeric value?
+    if [[ $# -eq 0 ]]; then 
+        cd "$HOME"
+    elif [[ `expr $1 + 1 2> /dev/null` ]]; then
+        for (( i=1; i <= $1; i++))
+        do
+            cd ..
+        done
+    else
+        \cd "$1"
+    fi
+}
+
+####
+# calles find with given param and type f
+#
+# @param string $1 - pattern you are searching for
+# @param [string $2] - path to serching in
+# @param [bool $3] - do not ignore dot files
+#
+# dot exclusion taken from: https://www.linuxquestions.org/questions/linux-general-1/find-and-excluding-all-hidden-directories-910578/
+#
+# @author stev leibelt
+# @since 2013-03-08
+####
+function net_bazzline_find_file ()
+{
+    if [[ $# -eq 1 ]]; then
+        find . -iname "$1" -not -path "*/.*/*" -not -name ".*" -type f 2>/dev/null
+    elif [[ $# -eq 2 ]]; then
+        find "$2"  -iname "$1" -not -path "*/.*/*" -not -name ".*" -type f 2>/dev/null
+    elif [[ $# -eq 3 ]]; then
+        find "$2" -iname "$1" -type f 2>/dev/null
+    else
+        echo 'No valid argument supplied.'
+        return 1
+    fi
+}
+
+####
+# calles find with given param and type d
+#
+# @param string $1 - pattern your are searching for
+# @param [string $2] - path to serching in
+#
+# @author stev leibelt
+# @since 2013-03-08
+####
+function net_bazzline_find_directory ()
+{
+    if [[ $# -eq 1 ]]; then
+        find . -iname "$1" -type d 2>/dev/null
+    elif [[ $# -eq 2 ]]; then
+        find "$2" -iname "$1" -type d 2>/dev/null
+    else
+        echo 'No valid argument supplied.'
+        return 1
+    fi
+}
+
+####
+# Show differences between two directories
+#
+# @param string $1 - path to first directory
+# @param string $2 - path to second directory
+# 
+# @author stev leibelt <artodeto@bazzline.net>
+# @since 2013-05-21
+function net_bazzline_diff_directory ()
+{
+    if [[ $# -eq 2 ]]; then
+        diff -qr "$1" "$2" | sort
+    else
+        echo 'No valid argument supplied.'
+        echo 'Try command directory1 directory2'
+        return 1
+    fi
+}
+
+####
+# adds "." to the beginning of the directory or file name
+# 
+# @param string $1 - file system object identifier
+#
+# @author stev leibelt <artodeto@bazzline.net>
+# @since 2014-07-31
+####
+function net_bazzline_hide_file_system_object()
+{
+    if [[ $# -eq 1 ]]; then
+# @todo validate if identifier is file or directory and if first character is not "."
+# @todo use net_bazzline_stringStartsWith
+        mv "$1" ."$1"
+    else
+        echo "Usage: net_bazzline_unhide_directory <directory_name>"
+        return 1
+    fi
+}
+
+####
+# adds "." to the beginning of the directory or file name
+#
+# @author stev leibelt <artodeto@bazzline.net>
+# @since 2014-07-31
+####
+function net_bazzline_unhide_file_system_object()
+{
+    if [[ $# -eq 1 ]]; then
+        IDENTIFIER="$1";
+# @todo validate if identifier is file or directory and if first character is "."
+# @todo use net_bazzline_stringStartsWith
+        #if [[ net_bazzline_stringStartsWith $IDENTIFIER "." ]]; then
+            mv $IDENTIFIER ${IDENTIFIER:1};
+            return 0
+        #else
+            #echo $IDENTIFIER" has to start with ."
+            #return 1
+    else
+        echo "Usage: net_bazzline_unhide_directory <directory_name>"
+        return 1
+    fi
+}
 
 ####
 # @param string $# - string name of directory you want to create
@@ -1710,6 +1630,86 @@ sleep 1
 done
 
 }
+
+####
+# begin of zfs section
+####
+
+####
+# @param string <name of the zfs pool>
+# [@param string <name of the snapshot>, default is current date
+####
+function net_bazzline_create_zfs_snapshot()
+{
+    if [[ $# -lt 1 ]]; then
+        echo 'invalid number of arguments'
+        echo '    net_bazzline_create_zfs_snapshot <name of the zfs pool> [<name of the snapshot>]'
+        return 1
+    fi
+
+    NAME_OF_THE_POOL="$1"
+
+    if [[ $# -gt 1 ]]; then
+        NAME_OF_THE_SNAPSHOT="$2"
+    else
+        NAME_OF_THE_SNAPSHOT=$(date +'%Y-%m-%d_%H-%M-%S')
+    fi
+
+    if sudo zfs snapshot -r $NAME_OF_THE_POOL@$NAME_OF_THE_SNAPSHOT; then
+        echo 'snapshot "'$NAME_OF_THE_SNAPSHOT'" created for pool "'$NAME_OF_THE_POOL'"'
+    fi
+
+    return $?
+}
+
+####
+# @param string <name of zfs pool>
+# @param string <name of the snapshot>
+####
+function net_bazzline_delete_zfs_snapshot()
+{
+    if [[ $# -lt 2 ]]; then
+        echo 'invalid number of arguments'
+        echo '    net_bazzline_delete_zfs_snapshot <name of the zfs pool> [<name of the snapshot>]'
+        return 1
+    fi
+
+    NAME_OF_THE_POOL="$1"
+    NAME_OF_THE_SNAPSHOT="$2"
+
+    if sudo zfs destroy -R $NAME_OF_THE_POOL@$NAME_OF_THE_SNAPSHOT; then
+        echo 'snapshot "'$NAME_OF_THE_SNAPSHOT'" deleted from pool "'$NAME_OF_THE_POOL'"'
+    fi
+
+    return $?
+}
+
+####
+# [@param string <path to zfs pool>]
+####
+function net_bazzline_list_zfs_snapshots()
+{
+    if [[ $# -lt 1 ]]; then
+        sudo zfs list -t snapshot
+    else
+        NAME_OF_THE_POOL="$1"
+
+        sudo zfs list -t snapshot | grep $NAME_OF_THE_POOL
+    fi
+}
+
+####
+# @param string <path to zfs pool>
+# [@param int number of snapshots to keep, default is 1]
+####
+function net_bazzline_rotate_zfs_snapshot()
+{
+    echo 'work in progress'
+}
+
+####
+# end of zfs section
+####
 
 ####
 # end of filesystem section
